rework PR workflow; update docs related to addressing failures

diff --git a/.github/workflows/plugin-pr-validate.yml b/.github/workflows/plugin-pr-validate.yml
--- a/.github/workflows/plugin-pr-validate.yml
+++ b/.github/workflows/plugin-pr-validate.yml
@@ -52,7 +52,6 @@ jobs:
                   mkdir pr-data
                   echo "$PR_NUMBER" > pr-data/pr-num.txt
                   echo ${{ github.event.pull_request.user.login }} > pr-data/pr-author.txt
-                  cp "$TARGET_FILE" pr-data/
 
                   # Validation failure can be noted by nonzero exit status
                   # (first part of script) or by the red x emoji in the output
@@ -61,10 +60,18 @@ jobs:
                   if (grep ❌ "$TARGET_FILE" ||
                         [[ "$VALIDATION_EXITED_NONZERO" = "failure" ]])
                   then
-                      printf "failed" > pr-data/validation-status.txt
-                      exit 1  # fail the action!  The downstream actions should still run.
+                      STATUS="failed"
+                      printf "\n\nPlease see the [documentation](https://natcap.github.io/invest-plugin-registry/docs/submission_process.html#if-tests-fail) for more information on what to do when tests fail. After addressing validation errors, you can re-run tests by commenting \`/run-validation\` on the PR" >> "$TARGET_FILE"
                   else
-                      printf "passed" > pr-data/validation-status.txt
+                      STATUS="passed"
+                  fi
+
+                  printf "$STATUS" > pr-data/validation-status.txt
+                  cp "$TARGET_FILE" pr-data/
+
+                  if [[ "$STATUS" = "failed" ]]
+                  then
+                      exit 1  # fail the action!  The downstream actions should still run.
                   fi
 
             - name: Upload artifact
